### ISSUE TITLE
An Orcish Incursion Concept made by fable-lake

### ISSUE THREAD

**Issue by fable-lake** [knyghtmare/An_Orcish_Incursion#6]
The campaign will takes place in the year 8 of Wesnoth (Like in Original AOI)

In the campaign, the idea is that the player should only play a group of warriors assigned at the beginning - The campaign according to this idea, just like Lord-Knightmare wrote in one of his concepts, is to be Expert Difficulty with Story Delve

The concept is not very gameplay, more a story, where you look at the huge role of Erlornas Sun Division during the first Orcs invasion.

In this concept, Erlornas is the heir of Wesmere, the founder of the Elven colony in these forests (In the original, Erlornas was said to come from an ancient lineage)

I read that the campaign received a lot of bad reviews for the shallowness of the plot and predictability (In fact, this was probably the author's intention from the beginning, it was only supposed to teach the basics of Wesnoth mechanics and I think it did a good job) I'm going to try to show that that the story of An Orcish Incursion can be emotional.

In the plot, I would focus more on presenting the tragedy of Erlornas than enriching this campaign with an overwhelming amount of Lore.

So this is my very Little Idea and story Concept for AOI

**Specialties:**

- No recruit (One team on all campaign set on the begining for example player can chose the number of his company unique units, this is Expert)
- Your company is recall on beginning of every scenario
 - Set some special abilities or AMLA for specific companions to made their present in story mode visible and see their loses not only in emotional sense but also in the gameplay
- No very big maps but detailed
- Campaign type would be more survival than normal fights

**Length:**

7 scenarios - 4 battle, 3 story

**Nature:**

Single player with little RPG elements

**Number of players:**

1

**Scenario 1
Story Scenario**

It is supposed to show the unsuccessful bloodless rebellion in the Wesmere forests, which was to introduce the rule of the old kings. Erlornas is a descendant and heir of Wesmere, the forest founder.

**Scenario 2
Story Scenario**

It is supposed to portray the judgment of the three lords on Erlornas, who, together with his followers, is about to be exiled, but a messenger comes to one of the Lords of the western provinces with the news of the dark marches of shadow creatures called Orcs. The council, considering the situation, determines a new punishment for the Elvish mighty, he and his squad are to pay off the sin of rebellion by providing and shielding, withholding the first Orcs marches so that Wesmere can build a defense.

**Scenario 3
Battle Scenario - Defeat Enemy Leaders**

It would depict the first encounter (Later called Erlornas Sun branch with shadow servant scouts). The elves are beginning to realize the danger. As he marches through the last free groves that form a barrier between the plains marking the border with the sea, Erlornas confronts his first battle with the commander of an orc scout unit. He wins and learns how to survive on the battlefield, smeared with the blood of enemies and friends buried in front of numerous oaks, alders and lime trees.

Mechanic

In this scenario, due to the small army of Erlornas and the fact that this is the first scenario, I believe that, as in one concept of Lord-Knightmare, when the player's units stand on an elven village, an alarm is raised and the inhabitants join the fight.

You can enrich the scenario by adding other events
As I'm not very good at building complex Events, I won't be giving you a lot of them.

**Scenario 4
Battle Scenario - Defeat Enemy Leaders**

The beginning of a lonely fight of a squad already slowly declining with three orc commanders called the Three Hammer Brothers (Their units would be created for the campaign) who enter a contemptuous conversation about the Elves, then describing the evil that will take place in the woods as they slaughter the Elves doomed to extinction.

Mechanic
Heroic battle on three fronts with three orc forces with different recruits. There can also be a priestess temple in the centre of the map.

You can enrich the scenario by adding other events

Sample Event

Orcs may have the ability to set fire to forests.

Sample Event

In the Erlornas squad, if one of the priestesses is still alive, an Event can be triggered, which shows how the spirits of nature are summoned to aid the Elves in the fight against the Orcs.

**Scenario 5
Battle Scenario - Make the Slaves Rebelion**

The journey of the Elves through the burned and looted villages near the evergreen groves of Wesmere, where in the distance you can hear a whip hitting the backs of captive Elves. Erlornas, taking his sword out with his men, murders all slave herdsmen, and then in the dungeons of the fortress he finds a mysterious Elf, who tells him about his journey with the eyes of emerald leaves and hair being one with the blowing wind. Hearing thanks from numerous liberators, Erlornas shows the direction of the free lands, where evil has not yet managed to re-infest and, separating with the mysterious minstrel, hears the words "The sun has born you, your hair is its rays, and your face is a glow that will blind those who wander in the darkness of the shadows"

Mechanic

Level even higher Orcs have the ability to summon slaves by force to fight, while Erlornas, defeating such a slave, frees him and brings him back to his side (player standing units commanded by Erlornas also free them after defeating Elvish slaves)

You can enrich the scenario by adding other events

**Scenario 6
Story Scenario**

The heir of Wesmere's company sets up their last camp near a hill looking out for the wide sea, but no Elf dares to climb it, and hidden under the cover of dark night, they remain silent, remembering the faces of their loved ones and those who are no longer with them. Erlornas, tired, stands in front of this hill and remembering his beloved Reilen and his parents, friends, unable to hold back tears, throws himself to his knees in front of a big tree and, pouring out a stream from his eyes, does not agree with the imminent death at the hands of the monsters of the night. In the end, resigned, sobbing, he rests against the tree trunk and looks at the faces of his companions saying "It's over, even I can not see any hope, and terror has filled my heart", but in the end one of the Elves muttered the old saying "When you only see a shadow around, look at heaven and see the glow of hope that will remain in you forever " Hearing these words, Erlornas begins to look at the sky full of stars and, sadly smiling in the face of the hope that has long since abandoned him, says "You are there, full of light and happiness of peace, and we are here in the face of terror and evil, which we are unable to present, forehead ". Finally, remembering the gift of his lady of the heart, he reaches for the pocket dirty with dust from which he takes the gift out. A silver ring with a snow-white jewel, and when he looks at it, he remembers Reilen's face and imagines what their unborn child will look like, remembers once again their happiness, which he refused to both of them when he set off on this suicidal journey, he remembers everyone who participated in the his way through life, smiling he finally mumbled "Thank you for everything ... Thank you for being by my side all the time", he spoke the words and immediately put the ring on his finger and after a while said a soft farewell "I'm sorry". Finally, ready after a long silence, he wiped his crystal tears and, looking down from the sky on the faces of the last Elves accompanying him, was ready, ready to come to terms with death, to fight for the lives of all those who accompanied him on his journey. To fight for the future of his loved ones. "I am Erlornas, the heir of Wesmere, all my life I wanted the good of all of us, I strove for this, I followed this path, but tomorrow it will be time to fulfill my obligation to my people, tomorrow we may die, we may die loaded on poisoned blacks, but we will fight by our side until the end, we will fight for our families, will you go this last time with me, comrades, will you stand with me this last time against the beasts from the sea whos come to pillage, murder and slave our families, make from them the shadows of former glory, if my death can give enough time to protect them, I will do it, I will slaught all this monsters and never let them win, even if this will sign my end, even if the cost is never united with Reilen, because I fight for her, I fight for those were killed, our brothers and sisters, who would help them if we were not here? This Council made from the ones that never experienced the love to their kin that suffered here on the borders, letting them die? I will not be like them, I will give voice to those who can't anymore sing with us, for those who were left alone, I will ask again, will you join me this one last time? Will you give me your strength to carry it for those who were left alone and for those who will live in this world after US!? I ASK AGAIN DO YOU JOIN ME!?" These words were greeted loudly by everyone.

**Scenario 7
Battle Scenario - Resist X Turns**

The next day, when Erlornas stood this last time on a high hill overlooking the wide waters covered with the darkness of hundreds of enemy ships mooring at the shores. The elves no longer felt fear, grief had long cooled them down, and their fortitude had been strengthened last night. As the black cloud slowly climbed the hill towards the Elves. Erlornas without a word looked at his gift from his beloved, then kissed it as if dedicating it to her. Then he took from the scabbard the sword with which he was to write his story, and looking into the eyes of his companions for the last time before the last march, putting on his golden helmet and with the sword at his chest, without fear, he moved against the unbridled darkness, and carried his thunderous battle hymn in the air. he carried the Irdya Elves into battle for the last time, and around them shone a golden glow created from the fire of the soul of the Wesmere heir, who, using all his inner power, carried the hope of all dead Elves to fight the beasts born to hate.

The last scenario is to end the scene when the required turn limit is over and then an amazing blast of sunlight will occur, which will lead to the ending inscription - The End

Mechanic

An epic story ending where the player will have to show off their skills to survive on the battlefield

You can enrich the scenario by adding other events

**Epilogue**

Erlornas squad stopped the orc invasion for about month, killing hundreds of enemies born of darkness, but finally stood against the impossible, but the Elves, although forbidden by their law to mourn the exiles, composed a long song about the Elves, sons and daughters of light, the ward called, the branch of the Sun, or the branch of the son of Wesmere, who, like a mountain avalanche, destroyed the backwoods of enemies falling to the ground, never to rise again.

"Once, one day, the old day
I saw hills full of trees, clearings full of meadows, and among them warriors, warriors surrounded by the hope of the sun of inner heat, they did not say their name, but their leader stretched out his hand to me, and he was called Erlornas and he was proud, but with a beautiful interior, and when in I was entering friendly borders, I heard his battle hymn, and when I stood far away, I saw a light glow looming in the distance, pure as if made of gold, it was the beginning of the dawn of hope which they gave us and which we will never pay back to them until the last leaf day ... "- Unknown Rescued by Erlornas Poet

"Lonely they were abandoned, living in the shadow of their lives, they lived for others, their light shone for us, Hope of good for us, the last bright ray in the dark sky, but it was enough to bring us freedom and peace, it was them and not anyone else who gave us this beautiful life, thanking them, we will remember, because from now on they are with us forever, although the banished we remembered, they gave us this beautifull live ..." - Fragment of a Song about the branch of the Sun

Additionally, the whole idea here can modify the Current Main Maintainer of AOI Lord-Knightmare

As for the dialogues, I can try it in the future, if the idea works fine and will be accepted.

Personally speaking, I really liked writing this story and I hope to continue developing it even though I have many other projects.

**Comment by knyghtmare** [comment]
I have got to say. I do like this concept. A lot. 
Despite being designed for singleplayer, this concept has a potential to be a hybrid campaign, that is both single player and multiplayer. 4 scenarios is enough for MP and RPG SP as well.

Here are some adjustments:
> Scenario 1
> Story Scenario

> Scenario 2
> Story Scenario

Since these are both story scenarios, they can be combined, to one. the `[replace_map]` can be used to swap around maps and such.

> In this scenario, due to the small army of Erlornas and the fact that this is the first scenario, I believe that, as in one concept of Lord-Knightmare, when the player's units stand on an elven village, an alarm is raised and the inhabitants join the fight.

I guess army compositions can be like: 

| - | Player 1      | Player 2 | single-player mode |
| ----------- | ----------- | -------------------- | ---- | 
| Elvish Fighter      |   2   |  2 | 3 |
| Elvish Shaman   |     1   | 1 | 2 |
| Elvish Archer | 2 | 2 | 3 | 
| Elvish Scout | 1 | 1 | 2 | 
| Elvish Hunter | 1 | 1 | 2  |
| Elvish Acolyte | 1 | 1 | 1 |

i have trimmed down the unit count so that the squads can stay "small". Also, the Elvish Hunter and Elvish Acolyte and their advancements can be ported but they can be subbed in for Archers or Fighters. 

> In the Erlornas squad, if one of the priestesses is still alive, an Event can be triggered, which shows how the spirits of nature are summoned to aid the Elves in the fight against the Orcs.

I am assuming you have meant Faeries and Woses? Yes, it can be done.

> Level even higher Orcs have the ability to summon slaves by force to fight, while Erlornas, defeating such a slave, frees him and brings him back to his side (player standing units commanded by Erlornas also free them after defeating Elvish slaves)

Very interesting concept. Analogous to what the Ogre Kingdom add-on was doing. Doable. 

> Scenario 7
> Battle Scenario - Resist X Turns

One interesting thing which can be added here is a scoring system like the player(s) can get a numbered score based on their performance on turn limit ends. They can be scored in terms of units left alive, enemy units killed, types of enemy units killed and unit types they have on field. I have seen this done in one campaign and the code seems refactorable.

One other thing is that...What of Lormafel? That loyal Elvish Rider in scenario 1 who comes back in scenario 7 in the classic? He can be a useful hero here. Maybe another side character (a female elf maybe?) who can act as the commander of side 2 (if the hybrid thing is picked up)?

On follow-up question:
Do we make it for re-inclusion into mainline or...do we make it an awesome UMC?

**Comment by fable-lake** [comment]
> I have got to say. I do like this concept. A lot.
> Despite being designed for singleplayer, this concept has a potential to be a hybrid campaign, that is both single player and multiplayer. 4 scenarios is enough for MP and RPG SP as well.


 I thought more about singleplayer, better not to repeat the LoW situation, but this is something to think about. So far I think it would look like "Campaign with fresh mechanics for the new version of Wesnoth maybe with RPG elements", the Multiplayer version is also not bad, but relatively and theoretically moves the campaign away from mainline.


> Since these are both story scenarios, they can be combined, to one. the `[replace_map]` can be used to swap around maps and such.


Yes, this is definitely a good proposition, I admit that I am not an expert in WML, so I rather stick to classic and old solutions.


> I guess army compositions can be like:
> 
> -	Player 1	Player 2	single-player mode
> Elvish Fighter	2	2	3
> Elvish Shaman	1	1	2
> Elvish Archer	2	2	3
> Elvish Scout	1	1	2
> Elvish Hunter	1	1	2
> Elvish Acolyte	1	1	1
> i have trimmed down the unit count so that the squads can stay "small". Also, the Elvish Hunter and Elvish Acolyte and their advancements can be ported but they can be subbed in for Archers or Fighters.


The unit layout composition looks promising, 13 SP and 8 MP
I like the idea of ​​setting in SP
2 Shamans - Not too much, just right as they are strong support units.
3 Archers and Fighters - Non-overwhelming amount of infantry and major damage dealers.
2 Scouts and 2 Hunters - Two long-distance units with great mobility and the ability to quickly change fronts, and two hunters who are a preety strong semi support combat unit, good composition.
1 Acolyte - I honestly don't know what to think, I have no experience with this unit, but using the Wesnoth unit database seems to be a good offensive arcane unit to weaken enemies in favorable positions, good thought.
Overall - 13 units made from preety useful branch which with good management can win hard battles, Nice.

Multiplayer Concept units placement is slightly bigger overall 16 but understandable because plays two different persons and strategy and decision of those can be little different so mean bigger loses.


> I am assuming you have meant Faeries and Woses? Yes, it can be done.


I didn't want to decide Woses or Faeries to give you a choice as:
Woses - Very good tankers with regenerate ability but with poor mobility and defense on all terrains, against Orcs preety weak especially Grunts and Archers with a fire attack not saying goblin pillager.
Faeries - Magick offensive units if I remember correctly, Nice damage dealers but with good defense support.
I think that a good idea would be to mix this concept and add some Woses and Faeries, not only one of them.


> Very interesting concept. Analogous to what the Ogre Kingdom add-on was doing. Doable.


Yep, preety similar to Great Steppe (Anyway similar climates) but suit well.


> One interesting thing which can be added here is a scoring system like the player(s) can get a numbered score based on their performance on turn limit ends. They can be scored in terms of units left alive, enemy units killed, types of enemy units killed and unit types they have on field. I have seen this done in one campaign and the code seems refactorable.


The idea looks great, counting defeated reminds me of the scenes with Gimli and Legolas in lotr, for sure this system would be quite a nice diversion and an incentive for a more creative strategy.


> One other thing is that...What of Lormafel? That loyal Elvish Rider in scenario 1 who comes back in scenario 7 in the classic? He can be a useful hero here. Maybe another side character (a female elf maybe?) who can act as the commander of side 2 (if the hybrid thing is picked up)?


I actually forgot about Lormafel… Well, I think the side character suits him or her quite well. I like the idea of ​​him or her as the general of a second-player faction - Not a new character and known to those who have played before and liked the old AOI. Lormafel as a woman? I think it's a good idea, a good contrast will come from Elf Man Erlornas and Elf women Lormafel, who is a supporting character of the main character and Hero unit at the same time (and in Multi as a commander of the second player, it works great)


> On follow-up question:
> Do we make it for re-inclusion into mainline or...do we make it an awesome UMC?


I think An Orcish Incursion should return to its righfull place that's mean mainline and be on a par with other campaigns and the one that people think is worth playing

**Comment by knyghtmare** [comment]
> I thought more about singleplayer, better not to repeat the LoW situation, but this is something to think about. So far I think it would look like "Campaign with fresh mechanics for the new version of Wesnoth maybe with RPG elements", the Multiplayer version is also not bad, but relatively and theoretically moves the campaign away from mainline.

Given the current opinions, most people disapprove of LoW in general. We have a chance to make a better hybrid campaign than LoW here, without the mistakes in design and plot. LoW is even open-ended now, with the final scenario in MP mode being catered towards Landar winning since Kalenz is deprived of his recalls as well as Cleodil and two-thirds of his recall list being given to the player controlling Landar. It's a mess really.

AOI rework has 4 scenarios (not counting the story) and a consistent player count (1 in SP, 2 in MP). It's length is ideal for a hybridization. Anyways, the focus should be on optimizing SP mode but MP mode can still be on the table.

> Multiplayer Concept units placement is slightly bigger overall 16 but understandable because plays two different persons and strategy and decision of those can be little different so mean bigger loses.

The unit count thing: I wish to keep both as 12. 12 in SP, 8 for each team in MP. It's just the right count, I guess. Not too many, not too few. Deciding the compositions can come later. more elven units from UMC can be added as well.

However, if we are targeting a re-inclusion into mainline, I am dubious about adding in Faeries, Elvish Hunters and Elvish Acolytes, since units lacking animations are going to catch an eye from the art director. However, we can see where it goes depends on who the next "content developer member" is.

> The idea looks great, counting defeated reminds me of the scenes with Gimli and Legolas in lotr, for sure this system would be quite a nice diversion and an incentive for a more creative strategy.

This bring about some engagement from the players. SP mode: players can share their score and see how they compared on a global scale. MP mode: the 2 friends can compare against each other just like Legolas and Gimli, or with other scores obtained by coop mode players.

> I actually forgot about Lormafel… Well, I think the side character suits him or her quite well. I like the idea of ​​him or her as the general of a second-player faction - Not a new character and known to those who have played before and liked the old AOI. Lormafel as a woman? I think it's a good idea, a good contrast will come from Elf Man Erlornas and Elf women Lormafel, who is a supporting character of the main character and Hero unit at the same time (and in Multi as a commander of the second player, it works great)

Yes, I can see why people would forget him. His appearance is rather brief. Anyways, his character staying in the rework isn't really important. A completely new character leading the second squad and/or acting as Erlornas's second would be nice. Maybe an Elvish Acolyte or female Elvish Archer. 

> I think An Orcish Incursion should return to its righfull place that's mean mainline and be on a par with other campaigns and the one that people think is worth playing

The first choice then, I guess a lot of things I had intended should be put on hold. Like I wanted to add in AMLA for all of the player(s)'s units and an item/equipment system, but I guess the AMLA one can be added in. As for the other, we can see. 

So, we have 

Scenario 1: Defeat invading orcs + spawning AI-controlled allies to turn the tide via village capping.
Scenario 2: Defeat enemy leaders + forest burning 
Scenario 3: Free all prisoners/incarcerated elves. Prisoners can be of other races as well. Maybe elves, dwarves, humans (from the green isle), defective goblins, etc. 
Scenario 4: Survival/Scoring, with enemy waves composed of orcs, ogres and goblins (I am not sure about Trolls as the orcs have just arrived on the shores of the Great Continent so I don't think they can get the trolls as ready allies. they can be added in wave comps though) Ogres, on the other hand, can appear. Nagas can be added as well. The waves can be randomised as well via Lua.

Yeah, it seems like an engaging variety.

Additionally, I think more orc/goblins/troll/orcish unit types can be added in since I have always felt the Northerners faction lacked variety. 3 orcish unit-lines, 9 Orcish units in total, counting the Nightblade. Goblins count as like 7.

**Comment by fable-lake** [comment]
> Given the current opinions, most people disapprove of LoW in general. We have a chance to make a better hybrid campaign than LoW here, without the mistakes in design and plot. LoW is even open-ended now, with the final scenario in MP mode being catered towards Landar winning since Kalenz is deprived of his recalls as well as Cleodil and two-thirds of his recall list being given to the player controlling Landar. It's a mess really.
> 
> AOI rework has 4 scenarios (not counting the story) and a consistent player count (1 in SP, 2 in MP). It's length is ideal for a hybridization. Anyways, the focus should be on optimizing SP mode but MP mode can still be on the table.


The LoW hybrid gameplay blanket itself is not bad and may give many players the option to go through a story campaign with another person, but the end result of this hybrid is another matter.
I didn't know that Cleodil would end up in multi joining Landar, and Kalenz recalls, these are huge mistakes that change story point of the campaign ... In fact, improving this campaign should be a Devs priority. I am not surprised that people want gameplay rework.

 Yeach, for AOI hybrid is not looking bad. The concept gameplay itself is more fresh and more about survival, It would be something distinctive from other campaigns and preety harder (Interesting is fact of making another levels difficulties for such a campaing)


> The unit count thing: I wish to keep both as 12. 12 in SP, 8 for each team in MP. It's just the right count, I guess. Not too many, not too few. Deciding the compositions can come later. more elven units from UMC can be added as well.
> 
> However, if we are targeting a re-inclusion into mainline, I am dubious about adding in Faeries, Elvish Hunters and Elvish Acolytes, since units lacking animations are going to catch an eye from the art director. However, we can see where it goes depends on who the next "content developer member" is.


About lacking animations for Hunter and Acolyte, if I remember correctly the UtBS had in older versions Hunters and was a mainline. I personally didn't much care about animations for units as long as main sprites are good. The attack animations and defence can be added in future. Anyway the Wesnoth is still improved in units matters, UtBS got a full new Elves faction. There is a need to make some brave actions to improve the game.
Once again anyway the Hunters and Acolyte are to think more carefully but their present would be very useful. 
By the way I wouldn't decide to add enormous amounts of units that are unbalanced well yet.


> This bring about some engagement from the players. SP mode: players can share their score and see how they compared on a global scale. MP mode: the 2 friends can compare against each other just like Legolas and Gimli, or with other scores obtained by coop mode players.


Yes, that sounds very fresh and modern, especially for the multi. Counting the defeated can be a lot of fun, although the concept of the plot is very depressing from an emotional point of view, and I have thought of adding some mystical elements to it, especially until Erlornas death. You can go both ways:
1. Erlornas and his companions are literally killed on the battlefield.
2. Erlornas and his party at the end of the last scenario's turn limit, transform into a solar bascule that causes destruction and panic among the orcs who retreat north ending their invasion which will later lead to the events of the second orc invasion in LoW. Hence the name of the sun's branch and their legend - I like this idea more, a mystical plot, just like with this mysterious poet.
That would explain the orcs settlement in the far north from the fear of great Elvish power.


> Yes, I can see why people would forget him. His appearance is rather brief. Anyways, his character staying in the rework isn't really important. A completely new character leading the second squad and/or acting as Erlornas's second would be nice. Maybe an Elvish Acolyte or female Elvish Archer.


I think if the multi concept is to be kept in mind there is a need for supporting character that is friends of Erlornas and his supporter. 
I would keep your idea about the Elvish female leader of faction two. I think that yeach if Acolyte in concept is only one unit, why not make it a general. Erlornas is an Elvish Lord unit which is unical so why should the second general be for example common Rider? It would be good if it also be a unical interesting unit, like Acolyte. Lormafel … This name, for real it could also be a female name, but the name can be easily invented. Then this female Elf could be someone like his advisor along with the general in story.


> The first choice then, I guess a lot of things I had intended should be put on hold. Like I wanted to add in AMLA for all of the player(s)'s units and an item/equipment system, but I guess the AMLA one can be added in. As for the other, we can see.


Yeach I would, like you say, advise to put in hold equipment system. But the AMLA system for example two Heroes could be Great, like in UtBS Kaleh and Nym. 
 

> So, we have
> 
> Scenario 1: Defeat invading orcs + spawning AI-controlled allies to turn the tide via village capping.
> Scenario 2: Defeat enemy leaders + forest burning
> Scenario 3: Free all prisoners/incarcerated elves. Prisoners can be of other races as well. Maybe elves, dwarves, humans (from the green isle), defective goblins, etc.
> Scenario 4: Survival/Scoring, with enemy waves composed of orcs, ogres and goblins (I am not sure about Trolls as the orcs have just arrived on the shores of the Great Continent so I don't think they can get the trolls as ready allies. they can be added in wave comps though) Ogres, on the other hand, can appear. Nagas can be added as well. The waves can be randomised as well via Lua.


I agree the prisoners can also be Dwarves, Elves and Humans because this is on the borders of Wesmere. Defective goblins? Nice one. From Lore point of view it is preety possible because Orcs despised goblins so they can also use them to slave work.


About Ogres and Trolls, the Lore is against Trolls cause they join Orcs freshly in the far North where they lived. Ogres, so I don't remember their genesis or from where they came to the continent, but they are similar to orcs so they can be along them.
Nagas are a good variety, as I think the navigational abilities of the orcs on the sea are quite poor, it may be that they led them to the continent.


> Additionally, I think more orc/goblins/troll/orcish unit types can be added in since I have always felt the Northerners faction lacked variety. 3 orcish unit-lines, 9 Orcish units in total, counting the Nightblade. Goblins count as like 7.


Northerners variety is poor, that's true, there could be added something fresh but balanced, like Troll Boulderlober level 3 for example or Ogre level 3. Units that had preety long development state. There is need fresh ideas. The Northerners is made up from strong tanker units and damage dealers without any support units only assassin's and leaders that are only ocassionaly units. There are also Nagas and Trolls very similar units to orcs, only Trolls are good damage dealers with regeneration abillity that made from them very strong units, and Nagas are water damage dealers. Even a Troll Shaman is a magick damage dealer.

**Comment by knyghtmare** [comment]
> . Counting the defeated

I was referring to the scoring system used in WOF. The scoring took into account the cost value of units killed and left alive at the end of the scenario and assigned a score value to each side and then compared them. There was also a minimum threshold score which had to be surpassed to be deemed victorious. 

> About lacking animations for Hunter and Acolyte, if I remember correctly the UtBS had in older versions Hunters and was a mainline. I personally didn't much care about animations for units as long as main sprites are good. The attack animations and defence can be added in future. Anyway the Wesnoth is still improved in units matters, UtBS got a full new Elves faction. There is a need to make some brave actions to improve the game.
Once again anyway the Hunters and Acolyte are to think more carefully but their present would be very useful.
By the way I wouldn't decide to add enormous amounts of units that are unbalanced well yet.

Lack of animations shouldn't be a problem. The main focus should be reworking AOI to be a proper story-driven RPG/small squad hybrid/SP campaign. I mean if it does get green lit for 1.17.x, it would probably be receiving some artwork.

> Erlornas and his companions are literally killed on the battlefield.
> Erlornas and his party at the end of the last scenario's turn limit, transform into a solar bascule that causes destruction and panic among the orcs who retreat north ending their invasion which will later lead to the events of the second orc invasion in LoW. Hence the name of the sun's branch and their legend - I like this idea more, a mystical plot, just like with this mysterious poet.
That would explain the orcs settlement in the far north from the fear of great Elvish power.

The first one would be believable and a tragic ending would be something fresh in wesnoth mainline. I think all campaigns have some "good" ending, with DiD being the only exception. So, an emotional and tragic end would be nice. Even if it doesn't make mainline, at least it says as a top quality UMC.

> Yeach I would, like you say, advise to put in hold equipment system. But the AMLA system for example two Heroes could be Great, like in UtBS Kaleh and Nym.

I was thinking of adding in AMLA trees for the 2 heroes: Erlonas and the unnamed female Elvish spellcaster, with 3 paths. Each path being a collection/chain of AMLA related to the three social classes among the elves. I did want to add specialised AMLA for regular level 3 elvish units as well. Doable without editing the unit files. I also wanted to add a special trait to the elves of this Sun Division so they need less XP to advance to make the AMLAs obtainable under 4 scenarios.

> Northerners variety is poor, that's true, there could be added something fresh but balanced, like Troll Boulderlober level 3 for example or Ogre level 3. Units that had preety long development state. There is need fresh ideas. The Northerners is made up from strong tanker units and damage dealers without any support units only assassin's and leaders that are only ocassionaly units. There are also Nagas and Trolls very similar units to orcs, only Trolls are good damage dealers with regeneration abillity that made from them very strong units, and Nagas are water damage dealers. Even a Troll Shaman is a magick damage dealer.

What I meant was adding more new goblin/orcs/ogre units from UMC so that the players get more variety in the enemy compositions.

**Comment by fable-lake** [comment]
> I was referring to the scoring system used in WOF. The scoring took into account the cost value of units killed and left alive at the end of the scenario and assigned a score value to each side and then compared them. There was also a minimum threshold score which had to be surpassed to be deemed victorious.


The number of defeats required to win the scenario sounds good. You can do an endurance scenario with the required number of orcs to defeat instead of a turn limit, either both at once, or a scenario to endure X turns.
But the scoring of the defeated should stay anyway.


> The first one would be believable and a tragic ending would be something fresh in wesnoth mainline. I think all campaigns have some "good" ending, with DiD being the only exception. So, an emotional and tragic end would be nice. Even if it doesn't make mainline, at least it says as a top quality UMC.


There are for sure not many tragic ending campaigns, but I also think the first one is more realistic but the final story events like the withdrawal of Orcs on the North and after its second invasion in LoW stays without too much change in Wesnoth history. In the end, this branch of the sun was doomed from the beginning, and Wesmere was then supposed to prepare the defense, and in the end the orcs were defeated.
But I think some mystical fragments should stay in the story but without a happy ending for Erlornas and company. Apparently from the beginning it will be known that Erlornas is going on a suicide joirney, but no one will be entirely sure until the last scenario. But this twist in the plot doesn't reduce the chances of mainline at all, I would rather say it increases.

By the way, but the SoF did not have a tragic ending? If I remember in the end everyone dies apart from Gryphon and Alanin.


> I was thinking of adding in AMLA trees for the 2 heroes: Erlonas and the unnamed female Elvish spellcaster, with 3 paths. Each path being a collection/chain of AMLA related to the three social classes among the elves. I did want to add specialised AMLA for regular level 3 elvish units as well. Doable without editing the unit files. I also wanted to add a special trait to the elves of this Sun Division so they need less XP to advance to make the AMLAs obtainable under 4 scenarios.


That sounds great, three AMLA paths for Heroes, but the campaign in plans is not too long, therefore the advancements are supposed to be rational to game length. 
Trait lowering required XP to level up? Sounds preety like a trait inteligent or you have in mind a stronger variation of that trait?
AMLA for lev 3 standard units is a nice idea, however there could be when for example standard fighter level up on second level could get some bonus to its standard level upgrades.


> What I meant was adding more new goblin/orcs/ogre units from UMC so that the players get more variety in the enemy compositions.


Having a variety of enemies is a good idea, but there is need to remember about a reasonable number of them. Orc spam is popular thing so variety would be nice. Anyway in UMC there is preety cool content for Gobs, Trolls and similar.

**Comment by knyghtmare** [comment]
> By the way, but the SoF did not have a tragic ending? If I remember in the end everyone dies apart from Gryphon and Alanin.

Oh, yes! I forgot about that...Yes, it is tragic..and the reworked one in 1.15.15 is harder. :(

> That sounds great, three AMLA paths for Heroes, but the campaign in plans is not too long, therefore the advancements are supposed to be rational to game length.

Yes, given that's only 3 scenarios, having AMLA trees seem rather redundant, unless the XP modifier is nerfed down to like 60% or so, players won't get beyond 3 AMLA or maybe 4. Maybe add in AMLA trees later as a final segment after scenarios and stuff are done? 

> Trait lowering required XP to level up? Sounds preety like a trait inteligent or you have in mind a stronger variation of that trait?
AMLA for lev 3 standard units is a nice idea, however there could be when for example standard fighter level up on second level could get some bonus to its standard level upgrades.

One challenging that can be done (but might cause an uproar) would taking away level 3 advancements via code and adding in AMLA for level 2 instead. It would be one give and take situation. It might be fun to do, but not sure the playerbase would approve of such drastic things.

Since LoW and AOI being very similar was one of the reasons of AOI getting demainlined, maybe making AOI a better example of a hybrid campaign might be worth it.

**Comment by fable-lake** [comment]
> Maybe add in AMLA trees later as a final segment after scenarios and stuff are done?


I think this is the best solution


> One challenging that can be done (but might cause an uproar) would taking away level 3 advancements via code and adding in AMLA for level 2 instead. It would be one give and take situation. It might be fun to do, but not sure the playerbase would approve of such drastic things.


This is an idea of quite drastic changes and I honestly wouldn't like it as a player, having a unit that cannot level up to level 3. Anyway, I think, as you wrote yourself, it is best to wait with AMLA until the final phase.


> Since LoW and AOI being very similar was one of the reasons of AOI getting demainlined, maybe making AOI a better example of a hybrid campaign might be worth it.


I would rather say that the reason for demainlined AOI was the lack of interesting content, that is: the story and gameplay, so only beginners have always visited this campaign, and those looking for gameplay and interesting stories played something else.
A hybrid campaign, as I wrote before, is not a bad idea and can be an interesting addition.

One more thing, I wrote the full story to AOI and uploaded the translated version of it on your discord.

**Comment by fable-lake** [comment]
> Maybe add in AMLA trees later as a final segment after scenarios and stuff are done?


I think this is the best solution


> One challenging that can be done (but might cause an uproar) would taking away level 3 advancements via code and adding in AMLA for level 2 instead. It would be one give and take situation. It might be fun to do, but not sure the playerbase would approve of such drastic things.


This is an idea of quite drastic changes and I honestly wouldn't like it as a player, having a unit that cannot level up to level 3. Anyway, I think, as you wrote yourself, it is best to wait with AMLA until the final phase.


> Since LoW and AOI being very similar was one of the reasons of AOI getting demainlined, maybe making AOI a better example of a hybrid campaign might be worth it.


I would rather say that the reason for demainlined AOI was the lack of interesting content, that is: the story and gameplay, so only beginners have always visited this campaign, and those looking for gameplay and interesting stories played something else.
A hybrid campaign, as I wrote before, is not a bad idea and can be an interesting addition.
